apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          image: 'juliawin/as1frontend'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-svc
  labels:
    app: web-frontend
spec:
  type: LoadBalancer   # NodePort
  ports:
    - port: 80 # 3000
      targetPort: 3000  # Container port
      # nodePort: 32000 # Externalport
  selector:
    app: web-frontend
---