apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
        - name: fast-api
          image: 'juliawin/as1backend'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: "ps_db"
            - name: POSTGRES_DB
              value: "ps_user"
            - name: POSTGRES_PASSWORD
              value: "SecurePassword123"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-svc
  labels:
    app: fast-api
spec:
  type: ClusterIP  
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort: 8000
  selector:
    app: fast-api
---